using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using DockerFactor.CLI.UI;
using Spectre.Console;
using Spectre.Console.Cli;

namespace DockerFactor.CLI.Commands;

public class ConnectCommandSettings : CommandSettings
{
    [CommandArgument(0, "<TOKEN>")]
    [Description("Cryptographic ephemeral pairing token generated by install.sh")]
    public string Token { get; init; } = string.Empty;
}

public class ConnectCommand : Command<ConnectCommandSettings>
{
    public override int Execute([NotNull] CommandContext context, [NotNull] ConnectCommandSettings settings)
    {
        TerminalRenderer.RenderHeader();

        if (string.IsNullOrWhiteSpace(settings.Token) || settings.Token.Length < 32)
        {
            AnsiConsole.MarkupLine("[bold red]Error:[/] Invalid pairing token format. Expected 256-bit hex token.");
            return 1;
        }

        AnsiConsole.Status()
            .Spinner(Spinner.Known.Dots)
            .Start("Validating cryptographic pairing token...", ctx =>
            {
                Thread.Sleep(1000);
                ctx.Status("Configuring local client state...");
                Thread.Sleep(500);
            });

        var configDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".dockerfactor");
        Directory.CreateDirectory(configDir);

        var configPath = Path.Combine(configDir, "config.json");
        var configContent = $$"""
        {
          "pairedAt": "{{DateTime.UtcNow:O}}",
          "tokenHash": "{{settings.Token[..16]}}...",
          "status": "Paired"
        }
        """;

        File.WriteAllText(configPath, configContent);

        TerminalRenderer.RenderSuccessBanner(
            "VPS Pairing Successful!",
            $"Local terminal connected securely using 256-bit token.\nConfiguration saved to: {configPath}"
        );

        return 0;
    }
}
